### ISSUE TITLE
Post Title disappears when editing post

### ISSUE THREAD

**Issue by viscosho** [Code4SA/health-e-story-db#10]
If I try to make any edits on a published post, the title of the post disappears. There are some console errors:
Uncaught Expected 1 elements matching '#healthe-new-online_syndications-form input[name="outlet"]' but found 0
14:45:47.772 healthe-syndication-db.js:8 Uncaught Expected 1 elements matching '#healthe-new-print_syndications-form input[name="outlet"]' but found 0
14:45:47.773 healthe-syndication-db.js:8 Uncaught Expected 1 elements matching '#healthe-new-radio_syndications-form input[name="outlet"]' but found 0
14:45:47.773 healthe-syndication-db.js:8 Uncaught Expected 1 elements matching '#healthe-new-tv_syndications-form input[name="outlet"]' but found 0

**Comment by jbothma** [comment]
Hi Virginia

Thank you for the issue. Yes - this plugin makes a lot of assumptions about plugins and setup specific to the wordpress installation it was intended for.

I've seen you've closed the issue - is there anything more we can help with?
